### PR TITLE
spanish related

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
can you do the rest for me...because i do not understand how fix this  &lt;a href=\&quot;https://github.com/Caballlero/\&quot;&gt;Carlos Gonzalez&lt;/a&gt;
thanks
EDIT; maybe like this:  <translation>[Crédito de traductor] Traducción al espanol por &lt;a href=\&quot;https://github.com/Caballlero/\&quot;&gt;Carlos Gonzalez&lt;/a&gt;
</translation>  ??

**Comment by jklingen** [comment]
Thanks, I will take care of this.

I agree, this looks a bit confusing - basically it is just an HTML link with all the special characters escaped

**Comment by ghost** [comment]
Thanks

**Comment by jklingen** [comment]
I fixed it within the other pull request, so I will just close this one. I just submitted the release to Jolla Store, it should become available soon, as soon as the QA has approved it.

You can also download the new version here: https://github.com/jklingen/space-inspector/releases

Thanks again for providing the translation, great job! :)

**Comment by ghost** [comment]
Thanks, you are awesome developer.

**Pull request closed without merging**
