### PR TITLE
Create space-inspector_sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Hi,

Great app! Swedish translation if wanted.

### CODE REVIEW

**Comment by eson57** [comment]
Couldn't make this translation string work, no matter what I did, so you might want to take a look at that.

screenshot-19-07-15-09-58-24

**Comment by jklingen** [comment]
Awesome! Thanks so much, I'll happily add the Swedish translation :) Seems that I have broken internationalization for this label. I'll have a look, thanks for the heads-up.
I would also like to add translation credits to the "About" page, something like "Swedish translation by ...". Would "Svensk översättning av..." work (that's what the translation machine offers)?

Please note that the next release will have to wait a few weeks, there's a lot of other stuff on my plate at the moment... But I'll take care of it as soon as possible.

Thanks again for your support :)

**Comment by eson57** [comment]
For once, machine translation is absolutely correct, and please take your time. Mine is already translated.  :)

**Comment by jklingen** [comment]
Finally took the time to get my SFOS dev environment up and running again. I will publish a new release soon, including one or two new features. Sorry for the looooong delay :-/

**Comment by eson57** [comment]
Thanks, great news!  :)

**Comment by jklingen** [comment]
Hey there, I am not sure if you're still using this app, or even the OS. If so: I have added a few changes for the next release, including a new entry page directly linking to storage places.

So in case you are still motivated, I'd be happy if you had another look at the new/modified translation strings. If not, never mind, I can give machine translation another try - still better than nothing ;-) 

Thanks again for providing the translation, I really appreciate that, even though it took me some time before I picked it up.

**Comment by eson57** [comment]
Of course I'm still using, OS and app both. I think I'm addicted.  ;)

**Pull request merged**
